[[module.imports]]
path = "github.com/hugomods/base"

[[module.imports]]
path = "github.com/apache/echarts"
[module.imports.mounts]
source = "dist/echarts.js"
target = "assets/mods/echarts/echarts.js"

[params.hugopress.modules.echarts.hooks.body-end]

[params.echarts]
width = "100%"
height = "400"
